inputs_def:
  - handle: model
    description: Input
    json_schema:
      enum:
        - tiny.en
        - tiny
        - base.en
        - base
        - small.en
        - small
        - medium.en
        - medium
        - large-v1
        - large-v2
        - large-v3
        - large
        - large-v3-turbo
        - turbo
      ui:options:
        labels:
          - Tiny (English)
          - Tiny
          - Base (English)
          - Base
          - Small (English)
          - Small
          - Medium (English)
          - Medium
          - Large V1
          - Large V2
          - Large V3
          - Large
          - Large V3 Turbo
          - Turbo
    value: medium
  - handle: device
    description: Use CUDA to enable hardware acceleration, otherwise use CPU
    json_schema:
      enum:
        - cpu
        - cuda
      ui:options:
        labels:
          - CPU
          - CUDA
    value: cuda
outputs_def:
  - handle: model
    description: Output
    json_schema:
      contentMediaType: oomol/var
    kind: model
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Whisper model
description: Loading the Whisper model
