inputs_def:
  - handle: model
    description: Input
    json_schema:
      enum:
        - tiny
        - base
        - small
        - medium
        - large
      ui:options:
        labels:
          - Tiny
          - Base
          - Small
          - Medium
          - Large
    value: small
  - handle: device
    json_schema:
      enum:
        - cpu
        - cuda
      ui:options:
        labels:
          - CPU
          - CUDA
    value: cuda
  - handle: dir_path
    json_schema:
      type: string
      minLength: 1
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: model
    description: Output
    json_schema:
      contentMediaType: oomol/var
    kind: model
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Whisper model
