inputs_def:
  - handle: segments
    description: Input
    json_schema:
      type: array
      items:
        type: object
        required:
          - text
          - avg_logprob
          - compression_ratio
          - id
          - no_speech_prob
          - seek
          - start
          - end
          - temperature
          - tokens
        properties:
          text:
            type: string
          avg_logprob:
            type: number
          compression_ratio:
            type: number
          id:
            type: integer
          no_speech_prob:
            type: number
          seek:
            type: number
          start:
            type: number
          end:
            type: number
          temperature:
            type: number
          tokens:
            type: array
            items:
              type: number
          words:
            type: array
            items:
              type: object
              properties:
                start:
                  type: number
                end:
                  type: number
                word:
                  type: string
                probability:
                  type: number
outputs_def:
  - handle: srt
    description: Output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Whisper segments to SRT
